# Generated by Django 4.1.5 on 2023-01-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_enquiry_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='auto_id',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
