# Generated by Django 4.1.5 on 2023-01-25 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_remove_enquiry_auto_id_remove_enquiry_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='received_by',
            field=models.ManyToManyField(related_name='received_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sent_by',
            field=models.ManyToManyField(related_name='sent_enquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
