# Generated by Django 4.1.5 on 2023-01-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_enquiry_received_by_enquiry_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='sent_by',
        ),
    ]
