# Generated by Django 4.1.5 on 2023-01-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_enquiry_received_by_remove_enquiry_sent_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='store.service'),
        ),
    ]
