# Generated by Django 4.1.5 on 2023-01-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_enquiry_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='email',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
