# Generated by Django 4.1.5 on 2023-01-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularity',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.enquiry'),
        ),
    ]
