# Generated by Django 4.1.5 on 2023-01-26 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_popularity_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularity',
            name='eventment_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='store.service'),
        ),
    ]
