# Generated by Django 4.1.5 on 2023-01-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='ratingss',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
