# Generated by Django 4.1.5 on 2023-01-27 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_service_ratingss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='ratingss',
        ),
    ]
