# Generated by Django 4.1.5 on 2023-01-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_service_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
    ]
