# Generated by Django 4.1.5 on 2023-01-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_rating_rating'),
        ('store', '0019_remove_service_rating'),
    ]

    operations = [
    ]
