# Generated by Django 4.1.5 on 2023-01-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_rating_rating'),
        ('store', '0021_alter_rating_rating'),
    ]

    operations = [
    ]
