# Generated by Django 4.1.5 on 2023-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_merge_20230130_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Popularity',
        ),
    ]
