# Generated by Django 4.1.5 on 2023-01-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_popularity_event_management_name_popularity_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularity',
            name='event_management_name',
        ),
        migrations.RemoveField(
            model_name='popularity',
            name='rating',
        ),
    ]
