# Generated by Django 4.1.5 on 2023-01-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('CUSTOMER', 'CUSTOMER'), ('EVENT_MANAGEMENT', 'EVENT_MANAGEMENT')], default='CUSTOMER', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='email'),
        ),
    ]
