# Generated by Django 4.1.5 on 2023-01-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0002_account_role_alter_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('event_management', 'event_management')], default='customer', max_length=30, null=True),
        ),
    ]
