# Generated by Django 4.1.5 on 2023-01-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='over_view',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='mediafiles'),
        ),
        migrations.AddField(
            model_name='account',
            name='team_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='work_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
