# Generated by Django 4.1.5 on 2023-01-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0004_account_over_view_account_place_account_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='mediafiles'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('event_management', 'event_management'), ('admin', 'admin')], default='customer', max_length=30, null=True),
        ),
    ]
