# Generated by Django 4.1.5 on 2023-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0011_remove_account_more_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('event_management', 'event_management'), ('admin', 'admin')], default='event_management', max_length=30, null=True),
        ),
    ]
