# Generated by Django 4.1.5 on 2023-02-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0012_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('event_management', 'event_management'), ('admin', 'admin')], default='customer', max_length=30, null=True),
        ),
    ]
