# Generated by Django 4.1.5 on 2023-02-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectaccount', '0013_alter_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
